# Generated by Django 4.1.7 on 2023-04-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=8)),
                ("prenom", models.CharField(max_length=16)),
            ],
        ),
    ]
