# Generated by Django 4.1.7 on 2023-05-04 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0006_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personnel",
            name="prenom",
        ),
        migrations.AddField(
            model_name="personnel",
            name="mach",
            field=models.CharField(
                choices=[
                    ("Genre", "Genre - à choisir "),
                    ("Homme", "Homme "),
                    ("Femme", "Femme "),
                    ("ND", "ND - ne préfaire pas ce prononcer"),
                ],
                default="Genre",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 4, 8, 51, 57, 271265)
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 4, 8, 51, 57, 249860)
            ),
        ),
    ]
