# Generated by Django 4.1.7 on 2023-06-04 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "computerApp",
            "0052_alter_machine_maintenancedate_alter_personnel_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 6, 4, 15, 35, 16, 942152)
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 6, 4, 15, 35, 16, 965184)
            ),
        ),
    ]
