# Generated by Django 4.1.7 on 2023-06-06 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0081_alter_machine_maintenancedate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnel",
            name="mail",
            field=models.EmailField(blank=True, editable=False, max_length=254),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 6, 6, 8, 47, 40, 935442)
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 6, 6, 8, 47, 40, 964302)
            ),
        ),
    ]
