# Generated by Django 4.1.7 on 2023-06-06 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0086_alter_machine_maintenancedate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="ip",
            field=models.GenericIPAddressField(default="0.0.0.0"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="mach",
            field=models.CharField(
                choices=[
                    ("PC", "PC - Run windows"),
                    ("Mac", "MAc - Run MacOS"),
                    ("Serveur", "Serveur - Simple Server to deploy virtual machines"),
                    ("Switch", "Switch - To maintains and connect servers"),
                ],
                default="PC",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 6, 6, 9, 56, 37, 150246, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="nom",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 6, 6, 9, 56, 37, 176602)
            ),
        ),
    ]
