# Generated by Django 4.1.7 on 2023-06-07 19:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0087_machine_ip_alter_machine_mach_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="appart",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="computerApp.personnel",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 6, 7, 19, 36, 1, 581132, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 6, 7, 19, 36, 1, 611831)
            ),
        ),
    ]
